### ISSUE TITLE
Secret should be set

### ISSUE THREAD

**Issue by andrewpsp** [kennashka/collegebookstore#1]
After running
``` npm install ```
and 
``` npm start ```

Getting the following error, original we  thought it was because MongoDB was not installed, this is actually a different error.

```
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
/Users/space-grade/pound_town/front_end_designs/collegebookstore/node_modules/express-jwt/lib/index.js:20
  if (!options || !options.secret) throw new Error('secret should be set');
                                   ^

Error: secret should be set
    at module.exports (/Users/space-grade/pound_town/front_end_designs/collegebookstore/node_modules/express-jwt/lib/index.js:20:42)
    at Object.<anonymous> (/Users/space-grade/pound_town/front_end_designs/collegebookstore/controllers/auth.js:59:25)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/space-grade/pound_town/front_end_designs/collegebookstore/routes/auth.js:4:50)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
[nodemon] app crashed - waiting for file changes before starting...


```
https://github.com/auth0/express-jwt/issues/26

**Comment by kennashka** [comment]
Add this to the backend .env file

` MONGO_URI=mongodb+srv://user:password@cluster0-leyqi.mongodb.net/test?retryWrites=true&w=majority
PORT=8000

DATABASE = mongodb://localhost/ecommerce

JWT_SECRET = yoursecrete`
